# Generated by Django 5.2.5 on 2025-08-13 15:51

import books.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("author", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("fiksi", "Fiksi"),
                            ("komik", "Komik"),
                            ("motivasi", "Motivasi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pdf_file", models.FileField(upload_to=books.models.book_pdf_path)),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to=books.models.book_cover_path
                    ),
                ),
                ("total_pages", models.PositiveIntegerField(default=0)),
                (
                    "keywords",
                    models.TextField(blank=True, help_text="Kata kunci hasil analisis"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to=books.models.book_pages_path)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
            ],
            options={
                "ordering": ["page_number"],
                "unique_together": {("book", "page_number")},
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "book")},
            },
        ),
    ]
